project:
  type: website

website:
  title: "Fall Risk Website"
  navbar:
    left:
      - href: Logistics.qmd
        text: Logistics
      - href: Nurses.qmd
        text: Nurses

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



